apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-trivy-scan
  labels:
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  params:
    - description: Reference of the image buildah will produce.
      name: IMAGE_NAME
      type: string
    - default: 'true'
      description: Flag specifying whether image should be built again.
      name: BUILD_IMAGE
      type: string
    - name: IMAGE_REGISTRY
      type: string
      default: 'NA'
      description: Image registry url.
      optional: true
    - name: CURRENT_GIT_TAG
      type: string
      default: ''
      description: Current version of the application/image in dev.
    - name: REPO_NAME
      type: string
      description: Name of the repository
      default: 'NA'
  workspaces:
    - name: source
  steps:
    - name: scan
      image: aquasec/trivy
      workingDir: $(workspaces.source.path)
      env:
        - name: IMAGE_REGISTRY
          valueFrom:
            secretKeyRef:
              name: docker-reg-creds
              key: url
              optional: true
      script: |
        if [ $(params.IMAGE_REGISTRY) != "NA" ]; then
          trivy image $(params.IMAGE_REGISTRY)/$(params.REPO_NAME):$(params.CURRENT_GIT_TAG)
        else
          trivy image ${IMAGE_REGISTRY}/$(params.REPO_NAME):$(params.CURRENT_GIT_TAG)
        fi        

        
