---
# Source: stakater-trivy-scan/templates/task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-trivy-scan
  labels:
    app.kubernetes.io/version: "0.0.7"
spec:
  params:
    - name: IMAGE_NAME
      description: Reference of the image buildah will produce.
      type: string
    - name: IMAGE_REGISTRY
      description: Image registry url.
      type: string
      default: 'NA'
      optional: true
  workspaces:
    - name: source
  steps:
    - name: scan
      image: aquasec/trivy
      workingDir: $(workspaces.source.path)
      env:
        - name: IMAGE_REGISTRY
          valueFrom:
            secretKeyRef:
              name: docker-reg-creds
              key: url
              optional: true
        - name: TRIVY_DB_PROXY_REPO
          valueFrom:
            secretKeyRef:
              name: docker-reg-creds
              key: proxyUrl
              optional: true
      script: |
        if [ $(params.IMAGE_REGISTRY) != "NA" ]; then
          trivy image --db-repository ${TRIVY_DB_PROXY_REPO} $(params.IMAGE_REGISTRY)/$(params.IMAGE_NAME)
        else
          trivy image --db-repository ${TRIVY_DB_PROXY_REPO} ${IMAGE_REGISTRY}/$(params.IMAGE_NAME)
        fi
